### ISSUE TITLE
"Warum Chrome?"-Box ist hinfällig

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#100]
Seit 1.4.6 unterstützt Tuvero auch andere Browser als Chrome. Die "Warum Chrome?"-Box auf der Startseite sollte entfernt werden.

Version: 1.4.7
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Ich möchte die Box noch nicht ganz entfernen. Chrome bietet ja wenigstens den Vorteil der Druckvorschau.

In Version 9870e7b7cf0b7847eea1874b532d79d11200ba2f behoben.
