### ISSUE TITLE
internetexplorer 11: Schweizerauslosung schlägt fehl, Grund wird in Konsole nicht angezeigt!

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#101]
Schweizer 1. und 2. Runde mit 9 Spielern geht
3. schlägt 6 mal fehl -> Grund  wird nicht in der Konsole angegeben

Version: 148
Benutzer: fabe

**Comment by elor** [comment]
Kann Fehler mangels json-Datei nicht reproduzieren.

Mit der Umstellung auf die neue Auslosung für das Schweizer System ist dieser Fehler vermutlich behoben. Bei Bedarf neuen Issue aufmachen.
