### ISSUE TITLE
IE: SmartScreen blockiert Tuvero-Skripte

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#103]
## Problem

SmartScreen blockiert sämtlichen JavaScript-Code ("einige ActiveX-Elemente") im Internet Explorer.

Als Ergebnis wird nur der Ladebildschirm angezeigt und keine einzige Zeile meines Codes ausgeführt.

Die selben Probleme können mit NoScript-Einstellungen oder -Erweiterungen auftreten.

## Lösungsansätze:
* noscript-Bereich im Loader, der auf eine Seite verlinkt, in der erklärt wird, dass JavaScript für Tuvero notwendig ist und wie man ihn in allen Browsern aktiviert
* Automatische Weiterleitung nach 30 Sekunden, die nach erfolgreichem Ausführen des ersten Codes deaktiviert wird
* Standard-Text, der darauf hinweist, dass die Seite in 2 Sekunden geladen werden sollte.
* "Sollten sie nicht automatisch weitergeleitet werden, klicken sie hier"

Am Besten alle vier Varianten einpflegen

Version: alle Releases
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Commit f822f5d:

* noscript-tag added for browser-based blocking
* static message added for extension-based blocking and script load errors

This circumvents the error for now. I will move it to 1.5, when the wiki is populated and there's actual information I can point to.

**Comment by elor** [comment]
"enable javascript" warning should be enough for informed users
