### ISSUE TITLE
Löschbutton für alle Anmeldungen

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#104]
Im Teams-Tab sollte ein Button verfügbar sein, der alle Anmeldungen löscht.

Der Unterschied zum "Neues Turnier"-Button besteht in seiner Logik: Er löscht einfach nur alle Teams und ist nur sichtbar, wenn kein Turnier läuft.

Benutzer: Jürgen Hatzenbühler

**Comment by elor** [comment]
Mit 97dada3 behoben
