### ISSUE TITLE
Web Components and Polyfills in place of continuous template builds

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#108]
Web Components are an essential part of HTML5, which tie in with the MVC model of tuvero and the need for encapsulation of individual views.

By using html5 imports during development and flattening them with e.g. Vulcanize, using the `webcomponents.js` polyfill where necessary, it's possible to test and deliver a working application in every step of development, while retaining small numbers of bundled files.

It remains to be seen whether CSS files can be directly merged into an imported web component by `r.js`. If not, manual adjustments will have to be made. Same goes for the js files `main.js` and `require.js`. This could reduce the number of files from 6 to 4:

* index.html
* favicon.png
* sprite.png
* manifest.appcache

Until then, my proprietary build system of Version 1.5 will have to be used.

Version: 1.5-dev
Browser: build system. polyfill required for safari and internet explorer
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Bei genauer Betrachtung sieht mir das nach einem Performance- und Bandbreitenproblem aus.
Tuvero bleibt vorerst monolithisch.
