### ISSUE TITLE
Schweizer System: Warnung, wenn Zahl der sinnvollen Runden erreicht wurde

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#110]
Beim Schweizer System gibt es eine maximale Zahl von Runden. Wenn sie überschritten wurde, sollte eine kleine Nachricht erscheinen, die davor warnt, dass alle weiteren Spiele sinnlos sind und keine ernsthafte Aussage erlauben.

Probleme mit Freilosen, Hoch/Runterlosen usw. sollten ebenfalls direkt angezeigt werden.

Version: 1.5.0-dev
Benutzer: Maik/Mike aus Berlin

**Comment by elor** [comment]
Nicht mehr heute... -> 1.5.4

**Comment by elor** [comment]
Vermeintlicher Fehler ist erneut aufgetreten. Zurück zu 1.5.3 damit.

**Comment by elor** [comment]
Mit 77ff2269daed7ee1841735ad7a774ff861ccc18e eingeführt.
