### ISSUE TITLE
NaN-Fehler im Schweizer System

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#111]
Seit der ersten Runde des Schweizer Systems tauchen NaN-Fehler auf, die durch Ranking und History propagieren.

Genaueres muss geklärt werden, wenn die Mail mit den json-Dateien endlich ankommt.

Version: 1.4.9
Browser: Google Chrome
Benutzer: Maik/Mike aus Berlin

**Comment by elor** [comment]
Optionen wurden zurückgesetzt (byepointswon/lost)

<https://github.com/elor/tuvero/blob/develop/legacy/scripts/ui/options.js#L32>

**Comment by elor** [comment]
Unter Nutzung der Version 1.4.10 wird dieser Fehler automatisch erfolgreich beseitigt.

Nach zwei Monaten kann man von einer ausreichenden Verbreitung der neueren Version ausgehen, sodass dieses Problem effektiv behoben ist.
