### ISSUE TITLE
RankingModel Tests müssen ausgebaut werden

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#114]
Die Tests von RankingModel, einer der zentralen Klassen von Tuvero 1.5, müssen massiv erweitert werden.

Aktuell werden bye(), correct(), reset(), resize(), restore(), save() und die extraDependencies vom Konstruktor nicht getestet. Einige Fehleingaben werden ebenfalls ignoriert.

Wenn das so weiter geht, passieren noch Fehler.

Version: 1.5.0-dev
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
`bye()`, `reset()`, `resize()`, `save()` und `restore()` werden inzwischen getestet.

Nun muss nur noch `correct()` getestet werden.

**Comment by elor** [comment]
Die Ranking-Tests und damit die Ranking-Klassen selbst sind seit commit d0041fda91bf6e96dacea002624afe82144fcd82 vollständig.
