### ISSUE TITLE
KO-Setzreihenfolge ist nicht vollkommen korrekt

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#116]
In der Auslosung der KO-Systeme liegt ein kleiner Fehler vor, der bei 16 Teilnehmern für falsche Paarungen im Halbfinale sorgt. Dort spielen, wenn immer der Beste gewinnt, Teams 1-3 und 2-4, anstatt 1-4 und 2-3

## Zitat des Einsenders:

Meiner Meinung nach müsste die optimale Setzliste für eine 16er KO-Runde wie folgt aussehen:
Achtelfinale  Spiel 1       1.-16.
                           Spiel 2       8.-9.
                           Spiel 3       5.-12.
                           Spiel 4       4.-13.
                           Spiel 5       6.-11.
                           Spiel 6       3.-14.
                           Spiel 7       7.-10.
                           Spiel 8       2.-15.
Sollten immer die Besserplatzierten gewinnen wäre dann
Viertelfinale  Spiel 1       1.-8.
                           Spiel 2       5.-4.
                           Spiel 3       6.-3.
                           Spiel 4       7.-2.
Halbfinale       Spiel 1       1.-4.
                           Spiel 2        3.-2.
Finale                                    1.-2.

bei einer 32er KO-Runde müsste die Setzliste wie folgt aussehen:
Sechszehntelfinale  Spiel 1     1.-32.
                                        Spiel 2     17.-16.
                                         Spiel 3     8.-25.
                                        Spiel 4       24.-9.
                                        Spiel 5      5.-28.
                                        Spiel 6      21.-12.
                                        Spiel 7      4.-29.
                                        Spiel 8      20.-13.
                                         Spiel 9     6.-27.
                                         Spiel 10   22.-11.
                                         Spiel 11   3.-30.
                                         Spiel 12   19.-14.
                                         Spiel 13    7.-26.
                                         Spiel 14    23.-10.
                                         Spiel 15    2.-31.
                                         Spiel 16     18.-15.
Bei deiner KO-Baum Setzliste treffen die Besten schon früher aufeinander.

Version: 1.4.10
Anhang: https://gist.github.com/e88cc6aa1aff811e40e5

**Comment by elor** [comment]
Siehe auch #143

**Comment by elor** [comment]
Mit 627bfca intern behoben. Wird mit #143 aktiv.

Auslosungsergebnisse:

32 Spieler:

    1-32
    16-17
    8-25
    9-24
    4-29
    13-20
    5-28
    12-21
    2-31
    15-18
    7-26
    10-23
    3-30
    14-19
    6-27
    11-22

16 Spieler:

    1-16
    8-9
    4-13
    5-12
    2-15
    7-10
    3-14
    6-11

8 Spieler:

    1-8
    4-5
    2-7
    3-6

4 Spieler:

    1-4
    2-3

13 Spieler:

    1-F
    8-9
    4-13
    5-12
    2-F
    7-10
    3-F
    6-11

Die Reihenfolge der Begegnungen ist identisch mit der des Einsenders, obwohl die Anzeigereihenfolge nicht gewährleistet werden kann. Der Algorithmus ist für beliebig viele Teams ausgelegt.
