### ISSUE TITLE
Begegnungen Setzen-Haken bleibt nicht erhalten

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#117]
Der Begegnungen setzen-Haken bleibt über die Runden hinweg nicht erhalten

Version: 1.5.0-b2

**Comment by elor** [comment]
Fehler wurde inzwischen behoben und kann in Tests nicht mehr reproduziert werden: Die Turnieroptionen werden korrekt gesetzt, ausgelesen und sogar automatisch gespeichert.
