### ISSUE TITLE
Spenden-Button auf Startseite

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#118]
Der Spenden-Button ist nur schwer zu finden. Er sollte auch auf der Startseite erscheinen, um die Serverkosten decken zu können.

Ein nicht-intrusiver Spendenknopf auf der Willkommensseite sollte auch vorhanden sein.

Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Mit 1059b29 erstmal in Angriff genommen.
