### ISSUE TITLE
Turnierstände von <1.4.10 sollten mit 1.5.0+ geladen werden können

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#120]
Dafür ist eine Autokonvertierung der Speicherformate notwendig.

Version: 1.5.0-b2
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Einzelne Schweizer Turniere können schon konvertiert werden (ef9e800)

Noch notwendig:

* KO-Turniere
* Hoch-/Runterlose
* Abhängigkeiten der Unterturniere (Globales Ranking)
* Korrekturen

**Comment by elor** [comment]
Korrekturen und explizit vorhandene KO-Spiele werden korrekt wiederhergestellt. (736f125)

Noch notwendig:

* Platzhalter-Matches (KO)
* Hoch-/Runterlose
* Unterturnier-Abhängigkeiten (TournamentListModel.startIndex und so)

**Comment by elor** [comment]
Es fehlen nur noch Hoch-/Runterlose. Siehe #154

**Comment by elor** [comment]
Mit 8f2f02d behoben.

Weitere Tests nötig, Fehler werden in separaten Issues gehandhabt.
