### ISSUE TITLE
"Turnier Laden"-Knopf schickt keinen Toast

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#122]
Wenn ein Turnier geladen wird, gibt es keinen sichtbaren Hinweis für den Nutzer.

Hier sollte zumindest ein Toast erscheinen, besser noch ins Team-Tab gewechselt werden. Nach Möglichkeit sollte auch das Turniersysteme-Tab angezeigt werden.

Version: 1.5.0-b2
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Mit c9b68d7 behoben:

* Turnier Laden-Knopf funktioniert wieder
* Nur sinnvolle Toasts werden angezeigt
