### ISSUE TITLE
Anmeldung Löschen --> Hinweis notwendig, dass man einen Spieler anklicken soll

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#123]
Wenn man "Anmeldung Löschen" gedrückt hat, sollte ein Hinweis erscheinen, dass man das Team anklicken muss.

Ein Toast, der so lang sichtbar ist, wie Löschen möglich ist, reicht.

Version: 1.5.0-b2
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
4ffd452: Toast eingeführt.

a642196: Text neben Löschen-button eingeführt
