### ISSUE TITLE
Autovervollständigungs-Datei für Spielernamen soll entfernt werden.

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#128]
Sie verwirrt und wird nie genutzt.

Version: 1.5.0-b2
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Option zum Laden von Spielernamen für die Autovervollständigung aus einer Date wurde mit 9c8f589 entfernt, weil sie keine Anwendung gefunden hat. Vorbereitete Spielerlisten können weiterhin im Teams-Tab geladen werden.
