### ISSUE TITLE
Dev-Konsole: "Zuerst angemeldete Teams gewinnen lassen"-Knopf

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#129]
Quasi "Runde ausspielen", bloß dass die Teams mit den niedrigsten IDs immer gewinnen.

Das hilft enorm bei manuellen Stresstests.

Version: 1.5.0-b2
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Ich vermisse den Knopf nicht. Won't fix.
