### ISSUE TITLE
"Gespeicherter Turnierstand kann nicht geladen werden": #reset-Link nicht nutzbar

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#130]
Die Tabs werden transparent über den Splash Screen gelegt, sodass die Links auf dem Splash-Screen nicht anklickbar sind.

Möglichkeiten:

1. andere Anzeigereihenfolge
2. z-index
3. `display: hidden` bei Fehler

Außerdem sollte es per selenium getestet werden!

Version: 1.5.0-b2
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Kann Splash Screen nicht unterhalb der Tabs lagern, weil er sonst von ihnen nach unten geschoben wird.

Variante *1.* geht so nicht.

**Comment by elor** [comment]
7a69f56: Methoden *2.* und *3.* werden gemeinsam verwendet
