### ISSUE TITLE
Bei Umbenennen von Turnieren oder Spielern: "Bitte Namen eingeben"-Toast

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#132]
Toast so lang anzeigen, bis der Name geändert wurde.

Version: 1.5.0-b2
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Mit c58c603 für Teamnamen/Spielernamen eingeführt

**Comment by elor** [comment]
Mit e22d0bf für Unterturniere eingeführt.
