### ISSUE TITLE
Schweizer System: Optionale Losbedingungen

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#134]
Losbedingungen sollten im Schweizer System optional sein. Sie machen auch nur mit Siegesgruppen wirklich Sinn.

Version: 1.5.0-b2
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Seit f122809 wieder im Backend vorhanden.

**Comment by elor** [comment]
Mit e9da3030346cc937d92e8750447c586bc6b3bf4b wieder eingeführt.

Losbedingungen sind im Frontend nur unter Verwendung von Siegesgruppen verfügbar, machen sonst auch keinen Sinn.

Die Arbeiten am Backend sind damit für Release 1.5.0 abgeschlossen.
