### ISSUE TITLE
Auslosung: Laufende Spiele automatisch öffnen

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#135]
Laufende Spiele sollten automatisch geöffnet werden, sobald der letzte Spieler zugelost wurde

Version: 1.5.0-b2
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Abgelehnt.

Ungewollte Sprünge zwischen Tabs verwirren den Erstnutzer mehr, als sie nutzen. Die 2 Sekunden Zeitersparnis lohnt während eines 8-Stunden-Turnieres einfach nicht genug. Besser ist, wenn die Turnierleitung nochmal eine direkte Übersicht hat.

Es wäre besser, im Turniersysteme-Tab eine Kurzübersicht des Turnieres zu zeigen (offene/geschlossene Spiele z.B.)
