### ISSUE TITLE
Eingabe-Felder für Ergebnisse und Korrekturen sind zu klein

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#138]
Die Eingabe-Fehler sollten optional eine größere Schriftart haben.

Version: 1.5.0-b2
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Alle Eingabefelder wurden mit 36c79280e992a7563bb2dffdc8458cf4f3a57b75 um fast 50% vergrößert
