### ISSUE TITLE
Turnierverlauf: Umschalten zwischen allgemeinen Listen und Spezial-Listen

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#141]
Wie in 1.4.10, wo man die "Spiele-Listen" nutzen konnte.

Sind keine spezialisierten Listen verfügbar, so die Spielelisten automatisch genutzt werden.

Version: 1.5.0-b2
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Mit 4bea6d469070fe182f5e94c6144852b5a82b9084 ermöglicht. Die eigentlichen Listen werden in separaten Issues verarbeitet (Fortschrittstabelle und KO-Modus)
