### ISSUE TITLE
KO-Turnier in MVC-Version

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#143]
Die KO-Turniere wurden noch keinem MVC-Rewrite unterzogen

Siehe auch #110, #96 und #30

Version: 1.5.0-b2
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Siehe auch #97

**Comment by elor** [comment]
KO-Baum wird mit cd8a67b korrekt generiert. Es fehlen noch Platzhalterspiele und die Visualisierung

**Comment by elor** [comment]
Visualisierung funktioniert.

Es fehlen noch Platzhalterspiele

**Comment by elor** [comment]
Mit cb4685a endlich wieder eingeführt.

Hat auch wirklich mehr als genug Zeit gefressen!
