### ISSUE TITLE
Rundensystem mit gerader Zahl von Teams führt zu Dopplungen nach der Hälfte der Spiele

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#149]
* Rundensystem
* Gerade Anzahl an Teams

Bei der Hälfte der Runden wird die erste Runde wiederholt, aber mit umgekehrten Teams.

Hier habe ich das Rutschsystem offenbar falsch umgesetzt.

Version: 1.5.0-b2
Benutzer: Fabe
Anhang: https://gist.github.com/c01d8a452b8a719c7e03

**Comment by elor** [comment]
Mit 79166c3 behoben. Weitere Modi kommen in späteren Versionen
