### ISSUE TITLE
Falsches Team nach Korrektur

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#150]
Nach einer Korrektur werden die falschen Teamnummern angezeigt.

Zitat des Einsenders:
> Wenn man ein Ergebnis korrigiert, wird die Korrektur den falschen Teams zugeordnet.
> 
> Beispiel:
> 
> Team #20 gegen Team #4 hat tatsächlich gespielt.
> Wird dieses Spiel korrigiert, dann listet Tuvero die Korrektur anschließend für die Teams #19 und #3 in der Übersicht.
> Damit verschiebt sich natürlich die gesamte Tabelle.

Fehler konnte bei schnellem Test nicht reproduziert werden.

Version: 1.5.0-b2
Benutzer: über Kai Angne eingesendet

**Comment by elor** [comment]
Weiterer Test:

Die falsche Teamnummer taucht nur in der Liste der Korrekturen auf. Dort wurde offenbar bei der Anzeige die ID nicht um 1 erhöht, um die richtige Nummer anzuzeigen.

**Comment by Kai-Angne** [comment]
Bestätigt - Nur in der Liste der Korrekturen unterhalb der Tabelle wird die Teamnummer um -1 dargestellt. Tabelle wird korrekt neu berechnet und History ist auch korrekt. 

Zur Eingabe weiterer Korrekturen ist allerdings ein Reload der History notwendig. 
(Chrome Version 44.0.2403.155 m (64-bit), Win 8.1)

**Comment by elor** [comment]
Die Darstellung der Teamnummern wurde mit 4e75a43 korrigiert.

Falsches Verhalten der Eingabemaske wird unter Issue #151 behandelt.
