### ISSUE TITLE
Änderung der Mindest/Maximalpunkte in den Optionen wird erst nach Neuladen umgesetzt

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#153]
Die Felder zum Eintragen der Ergebnisse werden erst nach einem Neuladen mit den neuen limits versehen.

Version: 1.5.0-b2
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Options sollten als PropertyModel implementiert werden. Code Reuse und so.

**Comment by elor** [comment]
Sinnlos. Wird durch #270 ersetzt.
