### ISSUE TITLE
reduce RLE complexity

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#154]
`core/scripts/rle.js` is neither understandable nor maintainable. It has to be split into multiple functions, properly named and commented.

Version: 1.5.0-b3
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Keine Zeit. Verschoben zu 1.5.5

**Comment by elor** [comment]
Kein Nutzen, zu viele Kosten.

Tests sind umfangreich genug, um eventuelle Probleme aufzudecken.

closed.
