### ISSUE TITLE
Anzeige der bisherigen Lose im Schweizer System

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#158]
Die bisher vergebenen Lose sollten beim Schweizer System immer mit angezeigt werden.

Vielleicht wäre das Speichern und Anzeigen per RankingView sinnvoll

Version: 1.5.0-dev
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Mit f9b6088 werden alle vergebenen Lose im Ranking per RankingVotesComponent zusammengefasst und in Stringform angezeigt.

Das Verhalten entspricht Tuvero 1.4, nutzt aber die Mechanismen des Rankings zur Aktualisierung, Verbreitung, Anzeige und Serialisierung.

Der "sollten immer angezeigt werden"-Teil wird weiterhin in #134 behandelt.
