### ISSUE TITLE
Ladefehler abfangen und das Überschreiben des Speicherstandes verhindern

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#159]
Tritt beim Laden ein Fehler auf, so wird der bisher geladene Zustand dennoch geschrieben und überschreibt somit den alten Speicherstand.

Das zerstört den Speicherstand und verhindert nutzerbestimmtes Vorgehen.

Version: 1.5.0-dev
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Mit db17458 behoben.

Es ist unglaublich, wie sehr das Debugging dadurch erleichert wird :-)
