### ISSUE TITLE
KO-Turnier: "Auslosen" schlägt fehl

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#160]
Der KO-Modus "Auslosen" geht nicht.

Fehlerausgabe in Ereignisleiste:

    Turnierfehler: unknown KO mode: shuffled
    
    Turnierfehler: initialMatches() failed

Version: 1.5.0-dev-c2ec27f9
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Fixed by 500612e
