### ISSUE TITLE
Notwendiges Feature: optionsbasierte Vorauswahl der verfügbaren Turniersysteme und -modi

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#162]
In den Target-Optionen sollte eine Vorauswahl an Turniersystemen und -modi getroffen werden, die beim Aufbau des Turniersysteme-Tabs berücksichtigt werden.

Damit kann man abhängig von den Sportarten unterschiedliches Verhalten freischalten.

Version: 1.5.0-dev
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Mit 80c38ee84c4fed0f591dcb34bcbd633ad5c05bbf abgeschlossen.

Es sind noch die üblichen Tests nötig, bis 1.5.0 veröffentlicht werden kann.
