### ISSUE TITLE
Mobil: Text und links haben unterschiedliche Größe

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#164]
Das betrifft die Hauptseite und alle Targets.

Version: 1.5.0-b3
Browser: Chrome for Android auf Moto G2
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Die Startseite sieht seit Release 1.5.3 ziemlich ok aus, und die Mindestbreiten der Tuvero-Targets lassen es vorerst auf dem Smartphone ganz ok aussehen. Damit wird dieser Issue nicht aktiv verfolgt.

Elegante Lösung: Tuvero-App für Android und iOS. Windows Phone wird nicht unterstützt werden.
