### ISSUE TITLE
TAC / nach Korrektur von Ergebnis werden Punkte addiert

### ISSUE THREAD

**Issue by Kai-Angne** [elor/tuvero#165]
Wenn man ein Ergebnis mehrfach korrigiert, dann wird immer ein bzw. zwei TAC Punkt(e) mehr dazugezählt. Probiert mit 8:7 –> 8:0 –> 8:7 –> 8:0.
 
Die Punkte für das Team mit dem ursprünglichen 7 Punkten bekommt dann 9, 11 und 13 Punkte und rutscht in der Tabelle entsprechend nach oben.

Version Tuvero TAC 1.5.0-dev

**Comment by elor** [comment]
Vorzeichenfehler in https://github.com/elor/tuvero/blob/c1364b1d335e3a60816d6dbeea7fea87c8a7c9d7/core/scripts/rankingtaclistener.js#L153

Dort sollte `-=` stehen:

    points += 1;

**Comment by elor** [comment]
Mit ddf2f79 behoben.

Nach Möglichkeit bitte testen und kommentieren

**Comment by Kai-Angne** [comment]
works - thx a lot
