### ISSUE TITLE
Nach Korrektur neue Auslosung von Paarungen

### ISSUE THREAD

**Issue by Kai-Angne** [elor/tuvero#166]
Anforderung von Anwender - habe mir keine genauen Gedanken dazu gemacht. 
Geht halt nur, wenn eine neue Runde ausgelost wurd aber noch keine Partie in einer neuen Runde gestartet wurde, aber in dieser Zeit ein Ergebnis korrigiert wurde. 

Korrektur bei älteren Partien (älter als vorletzte Runde), wirken sich ja auf die Tabelle und somit auf die nächste Auslosung aus.

**Comment by elor** [comment]
Ist abhängig vom Turniermodus.

* Rundenturnier -> kein Problem. Reihenfolge ist unabhängig von Ranking.
* Schweizer System -> Unnötige Neuauslosungen müssen vermieden werden. Überprüfung notwendig: Wäre die Auslosung trotzdem möglich gewesen? (Hängt mit #19 und #110 zusammen)
* KO-System: Komplett zurückrollen und geänderte Ergebnisse eingeben.
* Poolsystem: Wie KO.
* 

In jedem Fall muss der Nutzer vorher gefragt werden, ob das Turnier zurückgerollt werden kann.
Hierfür werden auch ordentliche Dialoge benötigt (#167)

**Comment by elor** [comment]
Möglicherweise Duplikat von #96

**Comment by elor** [comment]
Wird zusammen mit #195 behoben.
