### ISSUE TITLE
"Neuen Namen eingeben"-Toasts verschwinden nicht

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#168]
Bei der Nutzung von Tuvero TAC 1.5.0-rc1 häufen sich Toasts mit dem Inhalt "Neuen Namen eingeben", die sich nicht von selbst wieder schließen.

Vermutlich stammen sie vom wiederholten Öffnen und Abbrechen eines Unterturnieres oder vom Umbennenen mehrerer Spieler.

Version: 1.5.0-rc1
Browser: Chrome
Benutzer: Kai Angne

**Comment by elor** [comment]
Siehe #169 und #170 für weitere Informationen zum Fehler.

**Comment by elor** [comment]
Der Hinweis in #170 (hat mit Spielerzahl zu tun) deutet auf den Aufbau des Turniersysteme-Tab hin.

Die Spieler werden per Diff-Algorithmus dynamisch nach dem Ranking sortiert und die Turnierzeilen Bedarf neu erstellt. Dabei kann es sein, dass die Toasts nicht richtig aufgeräumt werden. Hier ist zu testen, ob `TournamentController.prototype.destroy()` von `TournamentView.prototype.destroy()` aufgerufen wird. Außerdem muss der namechange-Toast über `TournamentController.prototype.destroy()` geschlossen werden (`Toast.close()`)

Ich schau es mir heute Abend mal an.

**Comment by elor** [comment]
Mit f80268e behoben.

Sollte sich der Fehler dennoch reproduzieren lassen, bitte einen Kommentar hinterlassen.

**Comment by elor** [comment]
Fehler tritt auf, wenn man einen NewTournamentController-Button (Auswahl des Turniersystems) anklickt, während eine Turnier-Umbenennung im Gang ist.

**Comment by elor** [comment]
Sollte mit da29e3180fe198a9de512764e4a811baa1133e63 mal wieder behoben sein:

Eine destroy()-Funktion wurde scheinbar von der Prototype-Kette übergangen, was in JavaScript eigentlich nicht vorkommen sollte. Also übergehen wir hier Prototype-Kette. Nicht elegant, aber ich suche nicht noch drei weitere Stunden an dem blöden Fehler.

Siehe auch #177.

Sollte der Fehler der duplizierten Toasts immer noch auftreten, handelt es sich um ein anderes Problem als das hier behandelte. Bitte einen neuen Issue eröffnen und eine Schritt-für-Schritt-Anleitung zur Reproduzierung des Problems angeben.
