### ISSUE TITLE
Persistente Toasts

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#169]
erhalte ich, wenn ich ein Turnier im Schweizer System beende und in zwei Turniere splitte. Dabei spielt es keine Rolle, ob ich in ein Schweizer und eine K.O. Runde splitte, oder in zwei K.O. Runden. Es bleiben die Toasts mit "Neuen Namen eingeben" stehen. Toasts die evtl. dazwischen erscheinen, verschinden auch wieder.

Die Toasts bleiben auch bei Tab-Wechsel, Eingaben usw. stehen. 
Bei einem Reload der Seite verschwinden sie.

Gleiches passiert auch mit Firefox 43.0a2 Dev..

Version: 1.5.0-rc1
Browser: aktuelle Chrome u. Firefox
Benutzer: Kai

**Comment by elor** [comment]
Duplikat von #168
