### ISSUE TITLE
Persistente Toasts (2)

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#170]
Zum Nachvollziehen:
* die Toasts mit "Neuen Name eingeben" erscheinen erst, sobald man eine Runde im Schweizer System beendet und dann das Turnier splittet

* es recht dazu eine Runde im Schweizer-System durchzuspielen und dann zu beenden
* es wurde nicht in das Feld für den Turniernamen geklickt
* die Zahl dieser Toasts scheint mir der Zahl der Teilnehmer zu tun zu haben - nicht verifiziert

Version: 1.5.0-rc1
Browser: Chrome

**Comment by elor** [comment]
Duplikat von #168
