### ISSUE TITLE
Fortschrittsliste enthält keine Punktwertungen, nur den Platz

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#172]
Fortschrittslisten sollten eigentlich den Fortschritt anzeigen. Dafür ist die Anzeige der RankingComponents nötig.

Siehe auch #142 

Version: 1.5.0-rc2
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Mit 5fba3d95f8b7e7ea0b37e9d3929c1c0a26f040f1 behoben.

Erzeugt #178, welcher aber weniger schwer ist.
