### ISSUE TITLE
Manche Optionen können in die Presets verschoben werden

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#173]
Nicht alle Optionen müssen im Speicherstand mitgeführt werden. Sie sollten in die Presets verschoben werden.

Version: 1.5.0-rc2
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
In 1146d5a304f1d993c35153614b7d73086b4651e4 wurden alle Konstanten zu den Presets migriert.

Nur noch Optionen, die für etwaige Neuberechnungen oder Anpassungen der Turnierwertungen relevant sind, wurden beibehalten, um Modifikationen an Tuvero zuzulassen.
