### ISSUE TITLE
Replace GenericTournamentView with a factory function

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#177]
GenericTournamentView has no advantages over a factory function, but its prototype chain ignores destroy(), and the $view element is bound to two View instances.

This needs to be fixed by replacing it with a factory function.

Version: 1.5.0-rc2
Browser: Chromium 43.0.2357.130 Ubuntu 14.04 (64-bit)
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Ähnlich wie GenericTournamentHistoryViews in #229 erfüllen GenericTournamentViews in Zukunft möglicherweise wichtigere Aufgaben. Außerdem: Never change a running system.
