### ISSUE TITLE
Release Candidate 5 testen

### ISSUE THREAD

**Issue by elor** [elor/tuvero#180]
https://tuvero.de/1.5.0-rc4/

Nach ausführlichen Tests müssen wir entscheiden, ob 1.5.0 releasefertig ist.

**Comment by elor** [comment]
Release Candidate 4 ist jetzt verfügbar: https://tuvero.de/1.5.0-rc4/

**Comment by Kai-Angne** [comment]
einen "Toast" auf dich: "es wird nie so hart gecoded wie gedebuggt" :-). RC4 schaut gut aus, KO. Ergebniseingabe auf Tablet funktioniert. Toast-Problem scheint gelöst. Neue Gestaltung der Wertungsreihenfolge ist gut und geht auch am Tablet. Konnte bei kurzem Test keine Fehler feststellen.  Merci vielmals

**Comment by elor** [comment]
Ich finde zum Glück auch nur noch optische Fehler. Dankeschön :-)

**Comment by elor** [comment]
RC5 veröffentlicht. Wenn nichts dazwischen kommt, ist morgen Release-date.

https://tuvero.de/1.5.0-rc5/

**Comment by elor** [comment]
Version 1.5.0 veröffentlicht.
