### ISSUE TITLE
Überschrift wird auf falsche Seite gedruckt

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#198]
Situation:

Schweizer System mit 26 Teilnehmern, danach KO mit 8-9-9 Teilnehmern.
Beim Ausdruck des Turnierverlaufs wird die Überschrift des A-Turniers auf die vorherige Seite gepackt, statt auf die KO-Seite gedruckt zu werden.

Version: 1.5.0
Browser: nicht angegeben
Benutzer: Kai Klinkel

**Comment by elor** [comment]
Siehe #237 

Kann theoretisch auch im Haupttab eingeführt werden.
