### ISSUE TITLE
Rundenturnier: Es wird immer "Runde 1" angezeigt

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#201]
Die angezeigte Rundenzahl wird nicht erhöht.

Version: 1.5.0
Benutzer: Stephan Weigel

**Comment by elor** [comment]
Symptome:
* Richtige Runde steht im Backend.
* Das "Laufende Spiele"-Tab ist betroffen.
* Nach Neuladen der Seite ist die richtige Runde verfügbar

Mögliche Ursachen:
* update-event für die Runde wird nicht geschickt (hab ich überhaupt eins?)
* Frontend aktualisiert beim state update event nicht die Runde

**Comment by elor** [comment]
Mit 378e339 behoben
