### ISSUE TITLE
TAC: KO-Bäume werden standardmäßig versteckt

### ISSUE THREAD

**Issue by elor** [elor/tuvero#229]
Nebeneffekt der neuen TAC-Presets. Bitte um Feedback

**Comment by Kai-Angne** [comment]
hmmm - mir gefällt das nicht :-). Bei K.O. Runden finde ich den Baum übersichtlicher. 
Den Default für Spielelisten AN war mir für Runden im Schweizer System wichtig. Geht aber wohl nur entweder oder ... Da finde ich dann die Darstellung bei K.O. Runden ohne Baum deutlich verwirrender, als anders herum.

**Comment by elor** [comment]
Die KO-Spielelisten werden dann deaktiviert. Wer spielt schon KO nach Tabelle? :-)

**Comment by elor** [comment]
Mit 60de34047108725674546fc61d64bfe6c7ca4924 behoben. Das war einfacher als gedacht, und das Rendering ist jetzt einen Hauch schneller.
