### ISSUE TITLE
Laden von Teams aus simplen CSV-Dateien: teamsize wird zu groß

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#230]
Voranmeldung per <http://turniere.tuvero.de>

Beim Laden wird die teamsize ordentlich gesetzt, aber Mindest- und Maximalgröße wird nicht eingehalten und versteckte Elemente werden sichtbar

Version: 1.5.3 Basic
Browser: Chrome 48
Benutzer: Erik

**Comment by elor** [comment]
Mit 781a6e860b399383fed264683699221613a1cd4a behoben.
