### ISSUE TITLE
Direktes Laden von Voranmeldung vom Server

### ISSUE THREAD

**Issue by elor** [elor/tuvero#231]
Voranmeldungen auf http://turniere.tuvero.de müssen mit einen Klick in Tuvero zu öffnen sein.

Ideen:
- volles json-Austauschformat, wie beim Datei-Speichern
- optional: simples csv-Format, inklusive Turniername (auto-detektion)
- Öffnen per ajax-call aus Tuvero heraus (offline-Warnung)
- hash-target mit Webadresse, über die das Turnier geladen werden kann.
- http- Fehler code 405 bei Anmeldefehler, mit link zur Anmeldung und Turnierliste
- außerdem notwendig: Liste der verfügbaren Turniere (für aktuelle Anmeldung) + link zum abmelden und neu anmelden

Der selbe Mechanismus sollte in Zukunft auch für das Laden von Ranglisten und Elo-Zahlen genutzt werden können.

**Comment by Kai-Angne** [comment]
Hi Erik,

passt dazu meine Idee, abgeschlossene Turniere später darzustellen?

Genauer die Idee:

- wir archivieren und veröffentlichen ja Turnierergebnisse
- die Datei mit dem Endergebnis könnten wir online ablegen 
- und dann per Parameter an tuvero.de übergeben
- read-only oder gar eine abgespeckte Tuvero Version für diesen Zweck wäre chic, aber nicht zwingend notwendig

Allerdings habe ich auch noch eine andere Lösung über einen JSON Import und Aufbereitung der Darstellung über ein Template.

ciao
Kai

**Comment by elor** [comment]
Hi Kai,

Das liegt auch auf der Roadmap und ist einer der Gründe für global
eindeutige TimeMachine-Keys.

Meine inoffizielle Roadmap ist wie folgt:

* *Voranmeldung* (Styling fehlt noch. Sieht schauderhaft aus. Mal
http://turniere.tuvero.de angeschaut? Einfach schlimm ;-) )
* *1.5.4* (TAC-Fixes + Laden von Voranmeldungen)
* *kleiner Turnierkalender* (online + ical + rss)
* *Chrome-Webapp*, vll. auch Android-App
* *Ergebnisarchiv* (json + pdf)
* *1.5.5* (Bahnenauslosung + Ergebnis-Upload + *Tuvero Viewer*)
* *1.5.6* (Bugfixes + Devtools-Update)
* *Teamverwaltung* + *Vereinsverwaltung*
* *1.6* (Poule = Gruppenphase)
* *Ranglistenverwaltung* + *Elo*
* *1.6.1* (Elo Client-Code + Magic-Wertungen)
* *Tuvero Schach* (November)
* *Supermelee*

Ich brauche mal eine wirklich offizielle Roadmap mit Anbindung an die
nicht-öffentlichen Repositories...

Perspektivisch ist auch eine Live-Anzeige der Ergebnisse + Spieler-App
geplant:
"Du spielst jetzt auf Bahn 3 gegen Team 5.", "Dein letztes Spiel hast du zu
7 verloren", "Ergebnis online an Turnierleitung melden"

Aber:
* Der Tuvero-Client bleibt kostenlos
* Ich muss die Tuvero-Lizenz ändern (bleibt open source, aber nicht mehr
ganz so öffentlich)
* Server-Code wird nicht open source.

Was ist dir und der TAC-Gemeinschaft denn besonders wichtig?

Viele Grüße,
Erik

**Comment by elor** [comment]
Ich bin doof. Naja, ich lass die "Email" jetzt mal so stehen.

**Comment by elor** [comment]
Muss leider verschoben werden. Schaffe ich diese Woche nicht.

**Comment by elor** [comment]
Folgende Schritte müssen unternommen werden:

1. Server-Zertifikate installieren
2. API für turniere.tuvero.de anpassen
3. CORS-Header setzen
4. Anmeldung auf turniere.tuvero.de über Tuvero
5. Erstellte Turniere über turniere.tuvero.de-API auslesen
6. Startseite mit "Turnier importieren"-Knopf versehen
7. Auto-Upload der Speicherstände zu turniere.tuvero.de (mit Checkbox)

**Comment by elor** [comment]
Die verdammtem Zertifikate sind endlich da.

Punkte 1-3 sind umgesetzt.

**Comment by elor** [comment]
API-Tokens funktionieren jetzt anstandslos.

Nächste Schritte:
* Server-Code: APIBaseHandler aufräumen
* API: Turnier-Auflistung
* API: Turnier-JSON-Download mit allen Infos
* Tuvero: Eingeben und Speichern der Access Tokens
* Tuvero: Profilinformationen per API anzeigen
* Tuvero: Eigene Turniere per API anzeigen
* Tuvero: Turnier per API laden

**Comment by elor** [comment]
Login funktioniert:

Stand nach Commit b5c35ed63e071ae454591b6241d416b84691a538:
* Neue Access Tokens werden von Tuvero bezogen
* Tuvero kommuniziert über Tokens mit API (Aktuell nur Nutzername)
* Tokens können in Tuvero widerrufen (vergessen) werden
* in Turniere können Tokens gelöscht werden

TODO:
* Token speichern
* beim Start gespeichertes Token prüfen, bei Fehlschlag ausloggen
* Offline-Sonderregeln (bei vorhandenem Token eingeloggt, aber offline. Nutzernamen irgendwie merken)
* APIRequest-Klasse schreiben, die Kommunikation abstrahiert.

Begriffsklärung:
* Tuvero -> tuvero.de
* Turniere -> turniere.tuvero.de
* API -> api.tuvero.de

**Comment by elor** [comment]
Anmeldung auf dem Server funktioniert.

Nächster Schritt: Token speichern.

**Comment by elor** [comment]
Nachrichten können problemlos zwischen Server und Client ausgetauscht werden, Autovalidierung von Tokens ermöglicht automatisches Anmelden nach Login.
Aktueller Commit: 9b5228fb7a11129faad62aa59970e0cdbd25ac96

Nächster Schritt: Globale ServerModel-Instanz. Vermutlich Singleton.

**Comment by elor** [comment]
Kompatibilität der API zu Mobile Apps hergestellt. Token-Management in Servercode überarbeitet. Auto-Invalidierung von Tokens ergänzt. Aktueller Commit: 4bda0ec349df452eb3adbccf890c6b54fc7579de

**Comment by elor** [comment]
Transparentes Login zu Tuvero Turniere funktioniert. Aktueller Commit: 483d20f006985b37c917c8469182f59c58bc991d

**Comment by elor** [comment]
Persistente API Tokens werden akzeptiert und gespeichert. Storage-Klasse musste dazu auf Event-System umgeschrieben werden.
Genug für heute.

**Comment by elor** [comment]
Mit 5b7419fc58f94e41fc426bd2cee43ffe15c04c5f696f1a595da1c5e4650ba987ee566f55fcb26a238add1c9256db23775603589e7ea5 können Voranmeldungen direkt von Turniere.Tuvero.de geladen werden.

**Comment by elor** [comment]
* Alle Vorschauversionen neu kompilieren. TAC, Basic und Test haben noch die alte Logik
* Triggern des Herunterladens von Turnieren über GET-Parameter. Werden vom Server ignoriert.

* In Zukunft: Doppeltes Starten des gleichen Turnieres unterbinden

**Comment by elor** [comment]
Läuft! Tuvero TAC, Basic und Boule können Voranmeldungen direkt vom Server laden.

Technische Details:
* Turnier-IDs können doch in URL-Hash übergeben werden
* Tokens werden bei Bedarf automatisch vom Server geladen, sofern Nutzer angemeldet ist
* Login-Details vorerst auf Settings-Seite versteckt
