### ISSUE TITLE
Änderung "Teilnehmer" in "Teams"

### ISSUE THREAD

**Issue by Kai-Angne** [elor/tuvero#232]
Tuvero für TAC, 1.5.3 - Kosmetik
Seite NEW vor Wahl des Turniersystems / "Neue Turnierphase"
nach wählbarer Zahl der Teilnehmer "Teilnehmer" in "Teams" umbennen

merci
Kai

**Comment by elor** [comment]
Mit f3c6fbfcc1c58dfe6ffb1bdb9d580e785c5e033f umgesetzt
