### ISSUE TITLE
Internet Explorer: Type-Bibliothek funktioniert nicht

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#240]
Damit geht dort nix.

Ist doch schön, dass immerhin der IE noch das tut, was man von ihm erwartet: Nichts.

Version: alle
Browser: Internet Explorer 11
Benutzer: Erik

**Comment by Kai-Angne** [comment]
Man spürt leichten Frust bei dir :-)

Über 10 Jahre Website Erstellung haben mich irgendwann zu dem Punkt gebracht, an dem ich alle IE Versionen bei der Entwicklung mehr oder weniger ignoriere - wenn Bibliotheken etwas automatisch anpassen, dann gut, ansonsten Pech gehabt. Früher habe ich noch Kopfstände gemacht um irgendeine Funktion hinzubiegen. Jetzt teste ich nur noch in allen anderen Browsern, aber nicht mehr im IE - schont die Nerven gewaltig. 

Bei Tuvero sehe ich eine Funktion im IE als eh nicht zwingend notwendig. Lösungsansatz: Einen Browser Check einbauen und darauf hinweisen: "Bitte benutzen Sie einen guten Internetbrowser" ;-)

**Comment by elor** [comment]
Ursache: `String.match()` only returns one result, unless the RegExp parameter `g` is used.

@Kai-Angne Wird schon gemacht, aber bisher nur bei IE<9. Ist noch niemandem aufgefallen, was mich friedlich stimmt.
Eigentlich müsste man beim Start Grundfunktionen testen (oder Exceptions ordentlich catchen).

**Comment by elor** [comment]
Zweite Ursache: `String.match()` ignoriert capturing parentheses, sodass das Falsche gematcht wird.

@Kai-Angne Solang es nur kleine Dinge bleiben, passt das schon. Denke nicht, dass IE #239 mitmacht

**Comment by elor** [comment]
Nach einigem hin-und-her mit dedb1b712953f0ad39844d4dd6be6e7e2e354862 behoben.

Neue Version 1.5.4 wurde erneut hochgeladen, da keine substantiellen Änderungen vorgenommen wurde.
