### ISSUE TITLE
"Unzulässig Spielerzahl pro Team" beim laden der Teams aus Datei

### ISSUE THREAD

**Issue by Kai-Angne** [elor/tuvero#245]
Tuvero TAC 1.5.4

Meldung: "Unzulässig Spielerzahl pro Team" beim laden der Teams aus Datei.
Auch wenn ich Datei mit zwei Namen pro Zeile anlegen (Name A, Name B)

Händisches Anlegen geht aber ....

Grüße
Kai

**Comment by elor** [comment]
TAC hat nur einen Namen pro Team.

Mach Anführungsstriche um die komplette Zeile, um das Komma nicht mehr als Trennzeichen zu benutzen.

CSV: Komma ist Trennzeichen

**Comment by Kai-Angne** [comment]
Ich weiß was CSV ist :-) 

Anführungszeichen waren bisher nicht notwendig.
Mit Komma hatte ich es nur probiert (laut Blog Eintrag), um den Fehler einzugrenzen, falls mehr Namen pro Team erwartet werden. Wonach es halt bei der Fehlermeldung ausschaut. 

Ansonsten haben wir immer nur einen Namen pro Zeile - keine Kommas, keine Anführungszeichen.
Zeile wird mit Carriage Return & Line Feed abgeschlossen. 

Geht aber auch nicht mit einfachen und doppelten Anführungszeichen als Feldbegrenzer.

sorry ...

**Comment by elor** [comment]
Ok, ich schau es mir am Sonntag mal an

**Comment by elor** [comment]
Neue Testfälle eingeführt und CSV-Import neu geschrieben (e8b9c96733fbf790bf69b175c750f428df1416c3).

Hotfix-Release 1.5.5 kommt in ~10 Minuten.

@Kai-Angne Vielen Dank für den Hinweis; Sorry für das vorzeitige Schließen.
