### ISSUE TITLE
"Turnier aus Datei laden" entfernt alten Speicherstand nicht

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#249]
Stattdessen werden z.B. die Teams an bestehende Teams angehangen

Version: 1.5.5 Boule
Browser: Chrome 48
Benutzer: Erik
Anhang: https://gist.github.com/5c0dde727c1759d288b0

**Comment by elor** [comment]
Ursache: LegacyLoader ruft `State.clear()` nicht auf.

**Comment by elor** [comment]
Mit 017b74db23fcda61b8c2bfa76f1d61f3e6da4a88 behoben
