### ISSUE TITLE
monopol turnier

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#298]
hey  ihr lieben

komme nicht mehr ins monopol turnier rein bin zwar bei fb angemeldet,kann aber dennoch keine änderungen mehr tätigen. würtde gerne das turnier nochmal öffnen wegen einer weiteren anmeldung

grüße christoph nolden

**Comment by elor** [comment]
Access Token wird nicht akzeptiert. Ist vermutlich abgelaufen. Kann ich leider erst morgen Nachmittag reparieren.

**Comment by elor** [comment]
Facebook hat sein Rückgabe-Format von URL-kodiert auf JSON umgestellt. Das hätte man eher sehen müssen

**Comment by elor** [comment]
Schon länger gefixt.
