### ISSUE TITLE
Tuvero Online: 0-indizierte Teamnummern in Spieleliste

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#334]
Teamnummer aus alter json-Datei wird nicht um 1 erhöht.

Version: 2018-02-24
Browser: www.tuvero.de
Benutzer: Erik

**Comment by elor** [comment]
Begegnungen, Teams und Platzierungen in Tuvero Online generieren die Teamnummer alle über die selbe Zeile Quellcode:
<https://github.com/elor/tuvero/blob/develop/cli/commands.js#L6>

Darin wird die Teamnummer als ID+1 festgelegt.

Es sollte also überall das selbe angezeigt werden.

**Comment by elor** [comment]
Mit 7c62fb242d3f3e0e295f1a093ca21055bba18759 (Repository: Tuvero Online) behoben.
Ich habe die Id angezeigt, nicht die Nummer.

Man kann überlegen, die ID komplett aus Tuvero zu entfernen.
Sie hat ihren Zweck erfüllt und ist inzwischen weder eindeutig noch praktisch.
