### ISSUE TITLE
Spieler umbenennen: Neuer Name wird nicht in Fortschrittsliste übernommen

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#64]
Wird ein Spieler umbenannt, muss das Spielverlauf-Tab erst aktualisiert werden, bevor der Name aktualisiert wird.

Eine automatische Aktualisierung des Namens ist notwendig.

Version: 1.4.4
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Vermutlich mit d2570bab behoben
Getestet mit a2054dc
Funktioniert offenbar
