### ISSUE TITLE
Schweizer Fortschrittstabelle: Spielergebnis wird nicht angenommen

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#66]
Schweizer System, Fortschrittstabelle:

Kann ein laufendes Spiel nicht über die Fortschrittstabelle beenden, obwohl Änderungs-Dialog geöffnet werden kann.

Dieses Problem sollte sich mit der Neugestaltung des Spielverlauf-Tabs selbstständig lösen.

Version: 1.4.4
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Mit bf88d79 effektiv behoben.

Wird mit Bearbeitung von #142 aktiv
