### ISSUE TITLE
tabs.js/MVC-Rewrite: tabs.show() is called before the tabs have been initialized

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#67]
There's two cases:

* it's just a design flaw and strongly dependent on filename priorities
* the calling function has not checked whether tabs have been initialized

The error is reproducible when every script is minimized into one file (including jquery, but no optimization necessary), with the jquery paths option of requirejs set in a separate config.js file.

Version: 1.4.5:feature-jquery-update
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
`tabs.js` wurde mit dem MVC-Rewrite entfernt. Alle Tabs sind als Views umgesetzt und initialisieren sich selbst. Der Fehler ist somit behoben
