### ISSUE TITLE
Spielverlauf, "Hässliche Listen": kann Spielergebnis nicht ändern

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#71]
Spielergebnisse lassen sich nicht ändern, wenn man nicht im "Schöne Listen"-Modus des Spielverlauf-Tabs ist.

Sollte mit dem Big Rewrite hinfällig werden

Version: 1.4.5-dev
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Mit 1834fbb behoben
