### ISSUE TITLE
Turniersystem-Tab, ungerade Teams: grauer Hintergrund in letzter Zelle

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#74]
Die ausgedehnte letzte Zeile im Turniersysteme-Tab, die zur Top-Einrückung der Spielerlisten bei wenigen Spielern dient, hat bei ungeraden Spielerzahlen eine graue Hintergrundfarbe.

Eine weitere, speziell formatierte Zeile könnte eine Lösung darstellen.

Version: 1.4.5-dev
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Geringe Priorität, da rein optisch.

**Comment by elor** [comment]
Die ausgedehnte Zelle muss wieder in 1.5.0 integriert werden.

**Comment by elor** [comment]
Die langgezogene Zelle ist seit 74f00a1 wieder in 1.5.0 vorhanden.

Es wird keine zusätzliche Zeile nur für optische Zwecke geben. Damit wird dieses Feature abgelehnt, da technisch unverhältnismäßig schwierig und den Aufwand nicht wert.
