### ISSUE TITLE
Tabs: Reload versteckt Tabs oberhalb des Fensterrandes

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#75]
Beim Reload der Software schließt der Fensterrand standardkonform mit dem anchor ab (siehe location hash). Dieses Verhalten ist ungewollt und besteht seit der ersten Tab-Version vor drei Jahren.

Mit dem MVC-Rewrite stehen nun bessere Methoden zur Verfügung, die Tabs darzustellen.

Die vermutlich beste Lösung liegt darin, ein einziges Menü (aktuell: ein Menü pro Tab) zu erstellen, die Menüpunkte (Reiter) als Anker zu benutzen und die Tabs selbst über Klassen darzustellen und zu verstecken. Hashchange-Listener sind dabei ebenso notwendig, um unerreichbare targets zu vermeiden und mausfreie Navigation zu ermöglichen.

Version: Seit spätestens Version 1.0
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Spätestens mit 4c29836 behoben
