### ISSUE TITLE
Feature: Standard-Werte bei Spiel-Punkten

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#76]
Beim Beenden von Spielen steht aktuell ein Standardwert von 0. Hier sollte eine Target- oder Deployment-spezifische Option (options.js) zu Rate gezogen werden, die den Standardwert auf z.B. 8 (TAC) oder 13 (Boule) setzen kann.

Dies ist nur eine technische Implementierung. Die Frage nach den Vor- und Nachteilen muss für jedes Target separat entschieden werden.

Version: alle
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Note to self: Das bedingt die längst überfällige Implementierung eines ordentlichen mehrstufigen Konfigurations-Systemes.
