### ISSUE TITLE
Debugging Console: "Runde ausspielen" beendet nur ein Spiel

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#78]
Der "Runde ausspielen"-Knopf in der Dev-Console beendet ein einziges Spiel.

Dieses Verhalten hat vermutlich mit dem mehrfachen Re-Rendering des Game-Tabs beim Beenden eines einzigen Spiels zu tun und sollte mit dem MVC-Rewrite ohnehin behoben werden.

Version: 1.4.5
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Rechenaufwendig behoben. Mit dem MVC-Rewrite wird das noch schöner.
