### ISSUE TITLE
Firefox: cannot read transition lengths

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#79]
console: "could not read any transition lengths. What's your browser?"

Most likely part of the Toast system.

Version: 1.4.5
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Toasts wurden komplett neu geschrieben, Fehler besteht immer noch. Ist leider Firefox-spezifisch. Wird nur auf direkten Wunsch von Benutzern wieder eröffnet.
