### ISSUE TITLE
Firefox: Cache Manifest wird beim ersten Öffnen nicht gefunden

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#80]
Pro gecachter Datei erscheint ein Toast, das über ein fehlendes Cache Manifest informiert.

Das ist blöd und nervt. Mach es weg.

Version: 1.4.5
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Fehler besteht auch noch in Version 1.5.0-rc3.

**Comment by elor** [comment]
Mit fcf9490 behoben.
