### ISSUE TITLE
Firefox: Warnung über "Down"-Wert

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#81]
In der Konsole erscheint eine Warnung:

KeyboardEvent.key-Wert "Down" sollte nicht mehr verwendet werden und wird auf "ArrowDown" unbenannt. Für weitere Hilfe siehe https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent.key

Version: 1.4.5
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Außerhalb meines Einflussbereiches. Scheint mit jQuery zusammen zu hängen.
