### ISSUE TITLE
Internet Explorer 11 kann mit <scripts>-tags außerhalb von body nicht umgehen

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#82]
script-tags, die außerhalb von <head> und <body> stehen, werden vom Internet Explorer !MANCHMAL! nicht ausgeführt und führen somit in einigen Fällen zu Lade- und Darstellungsfehlern.

Sämtliche Tests und index-Dateien müssen überarbeitet werden.

Version: 1.4.6-dev
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Mit d35c56e067f6ea066f01804449b84911d21d31f8 behoben.

Alle script-Tags befinden sich nun im body, mit wenigen Ausnahmen, die im head sind.
