### ISSUE TITLE
Fortschrittstabelle: Freilos wird nicht angezeigt, die Spalten rutschen nach links durch

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#84]
In der aktuellen dev-Version werden die Freilose in der Fortschrittstabelle versteckt.

Ursache ist vermutlich der TabMenuView-Rewrite, bei dem viele CSS-regeln umgeschrieben wurden.

Version: 1.4.6-dev
Benutzer: Erik E. Lorenz
Anhang: https://gist.github.com/60d1077e42d580bfc07e

**Comment by elor** [comment]
Ein Teil des Fehlers wurde durch fehlerhafte Iteration verursacht: Die Team-Iteration begann bei 0, egal, welchen Rang der erste Spieler hatte. Relikt aus alten Zeiten.

Arbeite an Teil 2

**Comment by elor** [comment]
behoben mit bb088bd
