### ISSUE TITLE
turniersysteme-tab: gleiche Ränge werden nicht mehr versteckt

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#86]
Die Doppelspalte mit den Platzierungen zeigt zumindest bei mehreren Turnieren beide spalten an.

Version: 1.4.6-dev
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Fehler taucht in Version 1.4.6-rc1 (9b6f5ac) nicht mehr auf
