### ISSUE TITLE
Internet Explorer: Math.sign() existiert nicht (siehe TAC Ranking)

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#87]
Die sign()-Funktion ist in IE nicht definiert.

Recherchen notwendig, ob es im ECMA5-Standard ist.

Version: 1.4.6-dev

**Comment by elor** [comment]
Es handelt sich um ECMAScript 6 und wird deshalb nicht von allen Browsern unterstützt.

Eigene Funktion geschrieben.
Behoben mit a23cae1
