### ISSUE TITLE
Anmeldung wird nicht geschlossen

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#89]
Anmeldung wird nicht geschlossen nach beginn des turniers bzw. einer runde ... ie und Chrome sind betroffen

Version: 1.4.6-dev
Benutzer: fabe

**Comment by elor** [comment]
Aktuelle Release-Version 1.4.5 ist ebenfalls betroffen. Irgendwo fehlt ein ClassView.

Das Entfernen von Teams ist durch diesen Fehler im laufenden Turnier ebenfalls möglich und führt zu unvermeidbaren Problemen.

**Comment by elor** [comment]
Mit a24ba5b behoben
