### ISSUE TITLE
Kann KO Turnier nicht umbenennen

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#92]
Kann KO Turnier nicht umbenennen bzw. den namen bestätigen und speichern!

Benutzer: fabe
Anhang: https://gist.github.com/ade94f840c3ec3889555

**Comment by elor** [comment]
Kann den Fehler nicht reproduzieren. (Chrome 40.0.2214.111 und Firefox 35.0.1, Tuvero 1.4.6-c332dd4)

Welcher Browser wurde benutzt?
Welche Browser-Version?
Welche Tuvero-Version?
Was sagt die Debugging-Konsole?

**Comment by elor** [comment]
Mangels Nutzereingabe, die im direkten Kontakt von Fabe verlangt wurde, kann der Fehler nicht bestätigt werden.

Bitte öffne einen neuen Issue, wenn der Fehler ab Version 1.5 weiterhin besteht.
