### ISSUE TITLE
Teams aus Datei laden: Umlaute werden nicht richtig erkannt

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#93]
Werden Teams mit Umlauten aus einer Datei in die Teamliste geladen, so werden die Umlaute falsch formatiert.

Betrifft mindestens Firefox und Chrome

Version: 1.4.5, 1.4.6-dev
Benutzer: Anka

**Comment by elor** [comment]
Mit f1a489e behoben:

Zuerst wird die Datei als latin-1 geladen, und dann wandelt Tuvero einzelne Buchstabenfolgen in utf-8 um. Damit sollte das Problem vorerst behoben sein.
