### ISSUE TITLE
TAC-Entwicklerkonsole: "Runde ausspielen" kann kein Spiel beenden

### ISSUE THREAD

**Issue by boulesuser** [elor/tuvero#94]
Die Punktzahl, die von den "Runde ausspielen"- und "Turnier durchspielen"-Buttons in die Spielfelder eingetragen wird, ist keine zulässige TAC-Punktzahl.

Version: 1.4.6-rc1
Benutzer: Erik E. Lorenz

**Comment by elor** [comment]
Mit 615570d behoben
